version: '3.9'

services:
  jupiter-usdc-price-alert:
    image: nicxx2/jupiter-usdc-price-alerts:latest
    container_name: jupiter-usdc-price-alerts
    restart: unless-stopped

    environment:
      # ✅ TOKEN CONFIGURATION

      # INPUT_MINT: Always USDC for dollar-based pricing
      INPUT_MINT: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v

      # OUTPUT_MINT: The token you want to monitor (REPLACE this!)
      OUTPUT_MINT: <YOUR_OUTPUT_TOKEN_MINT>

      # ✅ AMOUNT TO SIMULATE (in USD)
      USD_AMOUNT: 100

      # ✅ CHECK INTERVAL (in seconds)
      CHECK_INTERVAL: 60

      # ✅ ALERT TRIGGERS
      BUY_ALERTS: "0.00135,0.00130"
      SELL_ALERTS: "0.00145,0.00150"

      # ✅ PUSH NOTIFICATIONS
      NTFY_TOPIC: token-alerts
      NTFY_SERVER: https://ntfy.sh

      # ✅ REPEAT ALERTS AFTER X MINUTES (0 to disable)
      ALERT_RESET_MINUTES: 0

      # ✅ LOCAL TIMEZONE
      TZ: Europe/London

    logging:
      driver: "json-file"
      options:
        max-size: "2m" # Max size per log file (2MB)
        max-file: "5" # Keep up to 5 rotated logs (~10MB total logs)
